/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package s30p.view;

import java.util.List;
import javax.persistence.Query;
import model.Estados;

/**
 *
 * @author Aziz
 */
public class CadastroEmpreendimentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroImoveis
     */
    public CadastroEmpreendimentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("S30PPU").createEntityManager();
        tabbeCadempreendimentos = new javax.swing.JTabbedPane();
        panelCaracteristica = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        checkPiscina = new javax.swing.JCheckBox();
        checkParque = new javax.swing.JCheckBox();
        checkEspgourmet = new javax.swing.JCheckBox();
        checkSauna = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        checkChurrasqueira = new javax.swing.JCheckBox();
        checkQuadra = new javax.swing.JCheckBox();
        checkEspzen = new javax.swing.JCheckBox();
        checkPorteiro = new javax.swing.JCheckBox();
        checkAcademia = new javax.swing.JCheckBox();
        checkSlfesta = new javax.swing.JCheckBox();
        checkBrinquedo = new javax.swing.JCheckBox();
        checkInterfone = new javax.swing.JCheckBox();
        checkPlayground = new javax.swing.JCheckBox();
        checkSljogos = new javax.swing.JCheckBox();
        checkCinema = new javax.swing.JCheckBox();
        checkCntgas = new javax.swing.JCheckBox();
        checkEstacionamento = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        checkRevest101 = new javax.swing.JCheckBox();
        checkColonial1 = new javax.swing.JCheckBox();
        checkPintura1 = new javax.swing.JCheckBox();
        checkSemir1 = new javax.swing.JCheckBox();
        checkNascente1 = new javax.swing.JCheckBox();
        checkPoente1 = new javax.swing.JCheckBox();
        checkNorte1 = new javax.swing.JCheckBox();
        checkSul1 = new javax.swing.JCheckBox();
        checkEmconst1 = new javax.swing.JCheckBox();
        checkInquilino1 = new javax.swing.JCheckBox();
        checkPropreside1 = new javax.swing.JCheckBox();
        checkVazio1 = new javax.swing.JCheckBox();
        panelEndereco = new javax.swing.JPanel();
        lblLogradouro = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        lblNum = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbEstados = new javax.swing.JComboBox();
        lblCidade = new javax.swing.JLabel();
        cbCidades = new javax.swing.JComboBox();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblPtReferencia = new javax.swing.JLabel();
        txtPtReferencia = new javax.swing.JTextField();
        panelDescricao = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblProprietario = new javax.swing.JLabel();
        lblCondominio = new javax.swing.JLabel();
        jcbProprietario = new javax.swing.JComboBox();
        jcbCondominio = new javax.swing.JComboBox();
        lblTipo = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        lblTmpoconst = new javax.swing.JLabel();
        lblAreato = new javax.swing.JLabel();
        txtAreato = new javax.swing.JTextField();
        lblAreaut = new javax.swing.JLabel();
        txtAreaut = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblCondom = new javax.swing.JLabel();
        txtTpoconst = new javax.swing.JTextField();
        txtCondom = new javax.swing.JTextField();
        lblPavim = new javax.swing.JLabel();
        lblIptu = new javax.swing.JLabel();
        txtPavim = new javax.swing.JTextField();
        txtIptu = new javax.swing.JTextField();
        lblTotun = new javax.swing.JLabel();
        txtTotun = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblUnpandr = new javax.swing.JLabel();
        lblPzentrega = new javax.swing.JLabel();
        txtUnpandr = new javax.swing.JTextField();
        txtPzentrega = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblDatavenda = new javax.swing.JLabel();
        txtDtaven = new javax.swing.JTextField();
        lblComvalor = new javax.swing.JLabel();
        txtValorcom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbParceiro = new javax.swing.JComboBox();
        lblComarecp = new javax.swing.JLabel();
        txtComrec = new javax.swing.JTextField();
        lblValorrec = new javax.swing.JLabel();
        txtValorrec = new javax.swing.JTextField();
        lblComapagp = new javax.swing.JLabel();
        txtCompag = new javax.swing.JTextField();
        lblValorpag = new javax.swing.JLabel();
        txtValorpag = new javax.swing.JTextField();
        panelComplemento = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        scrollComplemento = new javax.swing.JScrollPane();
        txtComplemento = new javax.swing.JTextArea();
        panelDocumentacao = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblEscritura = new javax.swing.JLabel();
        txtEscritura = new javax.swing.JTextField();
        lblHabite = new javax.swing.JLabel();
        txtHatite = new javax.swing.JTextField();
        lblAverbacao = new javax.swing.JLabel();
        lblContrato = new javax.swing.JLabel();
        txtContrato = new javax.swing.JTextField();
        checkQuitado = new javax.swing.JCheckBox();
        checkExclusividade = new javax.swing.JCheckBox();
        checkFotos = new javax.swing.JCheckBox();
        checkOportunidade = new javax.swing.JCheckBox();
        lblPostagem = new javax.swing.JLabel();
        lblLocalchaves = new javax.swing.JLabel();
        lblOutrosdoc = new javax.swing.JLabel();
        txtDatapost = new javax.swing.JTextField();
        txtLocchaves = new javax.swing.JTextField();
        txtOutrosdoc = new javax.swing.JTextField();
        txtAverbacao = new javax.swing.JTextField();

        setClosable(true);
        setTitle("SU Software - Cadastro de Empreendimentos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Características"));

        checkPiscina.setText("Piscina");

        checkParque.setText("Parque");

        checkEspgourmet.setText("Espaço gourmet");

        checkSauna.setText("Sauna");

        jCheckBox2.setText("Elevador");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        checkChurrasqueira.setText("Churrasqueira");

        checkQuadra.setText("Quadra");

        checkEspzen.setText("Espaço Zen");

        checkPorteiro.setText("Porteiro");
        checkPorteiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPorteiroActionPerformed(evt);
            }
        });

        checkAcademia.setText("Academia");

        checkSlfesta.setText("Sl Festa");

        checkBrinquedo.setText("Brinquedoteca");

        checkInterfone.setText("Interfone");

        checkPlayground.setText("Play ground");

        checkSljogos.setText("Sl Jogos");

        checkCinema.setText("Cinema");
        checkCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCinemaActionPerformed(evt);
            }
        });

        checkCntgas.setText("Central gás");

        checkEstacionamento.setText("Estacionamento");
        checkEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEstacionamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPiscina)
                    .addComponent(checkParque)
                    .addComponent(checkEspgourmet)
                    .addComponent(checkSauna)
                    .addComponent(jCheckBox2))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkChurrasqueira)
                            .addComponent(checkQuadra)
                            .addComponent(checkEspzen)
                            .addComponent(checkPorteiro))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkInterfone)
                            .addComponent(checkAcademia)
                            .addComponent(checkSlfesta)
                            .addComponent(checkBrinquedo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkPlayground)
                            .addComponent(checkSljogos)
                            .addComponent(checkCinema)
                            .addComponent(checkCntgas)))
                    .addComponent(checkEstacionamento))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkPiscina)
                    .addComponent(checkChurrasqueira)
                    .addComponent(checkAcademia)
                    .addComponent(checkPlayground))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkParque)
                    .addComponent(checkQuadra)
                    .addComponent(checkSlfesta)
                    .addComponent(checkSljogos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkEspgourmet)
                    .addComponent(checkEspzen)
                    .addComponent(checkBrinquedo)
                    .addComponent(checkCinema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSauna)
                    .addComponent(checkPorteiro)
                    .addComponent(checkInterfone)
                    .addComponent(checkCntgas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(checkEstacionamento))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fachada e situação"));

        checkRevest101.setText("100% revestida");

        checkColonial1.setText("Colonial");

        checkPintura1.setText("Pintura");
        checkPintura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPintura1ActionPerformed(evt);
            }
        });

        checkSemir1.setText("Semi-revestida");
        checkSemir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSemir1ActionPerformed(evt);
            }
        });

        checkNascente1.setText("Nascente");

        checkPoente1.setText("Poente");

        checkNorte1.setText("Norte");
        checkNorte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNorte1ActionPerformed(evt);
            }
        });

        checkSul1.setText("Sul");
        checkSul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSul1ActionPerformed(evt);
            }
        });

        checkEmconst1.setText("Em construção");

        checkInquilino1.setText("Inquilino");

        checkPropreside1.setText("Proprietário reside");
        checkPropreside1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPropreside1ActionPerformed(evt);
            }
        });

        checkVazio1.setText("Vazio");
        checkVazio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkVazio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(checkRevest101)
                            .addGap(55, 55, 55))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(checkNascente1)
                            .addGap(87, 87, 87)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkEmconst1)
                        .addGap(63, 63, 63)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkColonial1)
                    .addComponent(checkPoente1)
                    .addComponent(checkInquilino1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkPintura1)
                    .addComponent(checkNorte1)
                    .addComponent(checkPropreside1))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkVazio1)
                    .addComponent(checkSemir1)
                    .addComponent(checkSul1))
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkRevest101)
                    .addComponent(checkColonial1)
                    .addComponent(checkPintura1)
                    .addComponent(checkSemir1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkNascente1)
                    .addComponent(checkPoente1)
                    .addComponent(checkSul1)
                    .addComponent(checkNorte1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkEmconst1)
                    .addComponent(checkInquilino1)
                    .addComponent(checkPropreside1)
                    .addComponent(checkVazio1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCaracteristicaLayout = new javax.swing.GroupLayout(panelCaracteristica);
        panelCaracteristica.setLayout(panelCaracteristicaLayout);
        panelCaracteristicaLayout.setHorizontalGroup(
            panelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracteristicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCaracteristicaLayout.setVerticalGroup(
            panelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaracteristicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbeCadempreendimentos.addTab("Característica", panelCaracteristica);

        lblLogradouro.setText("Logradouro:");

        lblNum.setText("Num:");

        jLabel1.setText("Estado:");

        cbEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadosActionPerformed(evt);
            }
        });

        lblCidade.setText("Municipío:");

        lblBairro.setText("Bairro:");

        lblCep.setText("C.e.p.:");

        lblPtReferencia.setText("Pt Referência:");

        javax.swing.GroupLayout panelEnderecoLayout = new javax.swing.GroupLayout(panelEndereco);
        panelEndereco.setLayout(panelEnderecoLayout);
        panelEnderecoLayout.setHorizontalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEnderecoLayout.createSequentialGroup()
                        .addComponent(lblPtReferencia)
                        .addGap(18, 18, 18)
                        .addComponent(txtPtReferencia))
                    .addGroup(panelEnderecoLayout.createSequentialGroup()
                        .addComponent(lblLogradouro)
                        .addGap(29, 29, 29)
                        .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNum)
                        .addGap(18, 18, 18)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblBairro)
                    .addGroup(panelEnderecoLayout.createSequentialGroup()
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade)
                            .addComponent(jLabel1)
                            .addComponent(lblCep))
                        .addGap(40, 40, 40)
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbCidades, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        panelEnderecoLayout.setVerticalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogradouro)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNum)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidade)
                    .addComponent(cbCidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCep)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPtReferencia)
                    .addComponent(txtPtReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        tabbeCadempreendimentos.addTab("Endereço", panelEndereco);

        panelDescricao.setPreferredSize(new java.awt.Dimension(710, 372));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do empreendimento"));

        lblProprietario.setText("Proprietário:");

        lblCondominio.setText("Condomínio:");

        jcbProprietario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aziz Sault", "Marcio Carrera", "Taiane Cristina" }));

        jcbCondominio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhum", "Portal da Pituba", "Varandas do Vale", "Bosque da Aldeia" }));

        lblTipo.setText("Tipo:");

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casa", "Apto", "Terreno", "Lote", "Village", "Loja", "Fazenda", "Sítio" }));

        lblTmpoconst.setText("Tmpo construção:");

        lblAreato.setText("Área total:");

        lblAreaut.setText("Área útil:");

        jCheckBox1.setText("Permuta");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        lblCondom.setText("Condomínio:");

        lblPavim.setText("Pavimentos:");

        lblIptu.setText("I.P.T.U.:");

        lblTotun.setText("Total UN.:");

        lblValor.setText("Valor:");

        lblUnpandr.setText("UN p/andar:");

        lblPzentrega.setText("Pz entrega:");

        txtUnpandr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnpandrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCondom)
                                .addGap(51, 51, 51)
                                .addComponent(txtCondom))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTmpoconst)
                                .addGap(51, 51, 51)
                                .addComponent(txtTpoconst, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPavim)
                            .addComponent(lblIptu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIptu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPavim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTotun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotun, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUnpandr)
                                    .addComponent(lblPzentrega))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPzentrega, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUnpandr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(lblCondominio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcbCondominio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(lblProprietario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcbProprietario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(lblTipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(lblAreato)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAreato, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(lblAreaut)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAreaut, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProprietario)
                    .addComponent(jcbProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCondominio)
                    .addComponent(jcbCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipo)
                    .addComponent(lblAreato)
                    .addComponent(lblAreaut)
                    .addComponent(txtAreato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAreaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTmpoconst)
                            .addComponent(txtTpoconst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPavim)
                            .addComponent(txtPavim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotun)
                            .addComponent(txtTotun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnpandr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCondom)
                            .addComponent(txtCondom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIptu)
                            .addComponent(txtIptu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPzentrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPzentrega)))
                    .addComponent(lblUnpandr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendas e comissões"));

        lblDatavenda.setText("Data da venda:");

        lblComvalor.setText("Valor da comissão:");

        jLabel4.setText("Parceiro:");

        jcbParceiro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblComarecp.setText("Comissão a receber %:");

        lblValorrec.setText("Valor:");

        lblComapagp.setText("Comissão a pagar %:");

        lblValorpag.setText("Valor:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComapagp)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatavenda)
                            .addComponent(jLabel4)
                            .addComponent(lblComarecp))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtDtaven, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(lblComvalor)
                                .addGap(30, 30, 30)
                                .addComponent(txtValorcom, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCompag, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(txtComrec))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblValorrec)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValorrec, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblValorpag)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValorpag)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatavenda)
                    .addComponent(txtDtaven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComvalor)
                    .addComponent(txtValorcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComarecp)
                    .addComponent(txtComrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorrec)
                    .addComponent(txtValorrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComapagp)
                    .addComponent(txtCompag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorpag)
                    .addComponent(txtValorpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDescricaoLayout = new javax.swing.GroupLayout(panelDescricao);
        panelDescricao.setLayout(panelDescricaoLayout);
        panelDescricaoLayout.setHorizontalGroup(
            panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescricaoLayout.createSequentialGroup()
                .addGroup(panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelDescricaoLayout.setVerticalGroup(
            panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescricaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        tabbeCadempreendimentos.addTab("Descrição", panelDescricao);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Textto complementar"));

        txtComplemento.setColumns(20);
        txtComplemento.setRows(5);
        scrollComplemento.setViewportView(txtComplemento);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelComplementoLayout = new javax.swing.GroupLayout(panelComplemento);
        panelComplemento.setLayout(panelComplementoLayout);
        panelComplementoLayout.setHorizontalGroup(
            panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComplementoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelComplementoLayout.setVerticalGroup(
            panelComplementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComplementoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        tabbeCadempreendimentos.addTab("Complemento", panelComplemento);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Documentação do imóvel"));

        lblEscritura.setText("Escritura:");

        lblHabite.setText("Habite-se:");

        lblAverbacao.setText("Averbação:");

        lblContrato.setText("Contrato:");

        txtContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContratoActionPerformed(evt);
            }
        });

        checkQuitado.setText("Quitado");

        checkExclusividade.setText("Exclusividade");

        checkFotos.setText("Fotos");
        checkFotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFotosActionPerformed(evt);
            }
        });

        checkOportunidade.setText("Oportunidade");

        lblPostagem.setText("Data postagem site:");

        lblLocalchaves.setText("Local das chaves:");

        lblOutrosdoc.setText("Outros documentos:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblOutrosdoc)
                        .addGap(18, 18, 18)
                        .addComponent(txtOutrosdoc))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lblAverbacao)
                                .addGap(18, 18, 18)
                                .addComponent(txtAverbacao))
                            .addComponent(checkQuitado)
                            .addComponent(checkFotos)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lblPostagem)
                                .addGap(18, 18, 18)
                                .addComponent(txtDatapost, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lblEscritura)
                                .addGap(28, 28, 28)
                                .addComponent(txtEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(lblLocalchaves)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLocchaves, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                            .addComponent(checkOportunidade)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHabite)
                                    .addComponent(lblContrato))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHatite, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(txtContrato)))
                            .addComponent(checkExclusividade))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscritura)
                    .addComponent(txtEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHabite)
                    .addComponent(txtHatite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAverbacao)
                    .addComponent(lblContrato)
                    .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAverbacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkQuitado)
                    .addComponent(checkExclusividade))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkFotos)
                    .addComponent(checkOportunidade))
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostagem)
                    .addComponent(lblLocalchaves)
                    .addComponent(txtDatapost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocchaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutrosdoc)
                    .addComponent(txtOutrosdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDocumentacaoLayout = new javax.swing.GroupLayout(panelDocumentacao);
        panelDocumentacao.setLayout(panelDocumentacaoLayout);
        panelDocumentacaoLayout.setHorizontalGroup(
            panelDocumentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocumentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDocumentacaoLayout.setVerticalGroup(
            panelDocumentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocumentacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        tabbeCadempreendimentos.addTab("Documentação", panelDocumentacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbeCadempreendimentos, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbeCadempreendimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCinemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCinemaActionPerformed

    private void checkPorteiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPorteiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPorteiroActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void cbEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadosActionPerformed
        Estados estado = (Estados) cbEstados.getSelectedItem();

        Query cidadesQuery = entityManager1.createQuery("Select c FROM Cidades c WHERE c.estadosIdestados = :idEstado");
        cidadesQuery.setParameter("idEstado", estado);

        List cidadesList = cidadesQuery.getResultList();
        cbCidades.removeAllItems();
        cidadesList.stream().forEach((cidade) -> {
            cbCidades.addItem(cidade);
        });
    }//GEN-LAST:event_cbEstadosActionPerformed

    private void checkPintura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPintura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPintura1ActionPerformed

    private void checkSemir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSemir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSemir1ActionPerformed

    private void checkNorte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNorte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkNorte1ActionPerformed

    private void checkSul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSul1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSul1ActionPerformed

    private void txtUnpandrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnpandrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnpandrActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void checkPropreside1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPropreside1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPropreside1ActionPerformed

    private void checkVazio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVazio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkVazio1ActionPerformed

    private void txtContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContratoActionPerformed

    private void checkFotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkFotosActionPerformed

    private void checkEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEstacionamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEstacionamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCidades;
    private javax.swing.JComboBox cbEstados;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JCheckBox checkAcademia;
    private javax.swing.JCheckBox checkBrinquedo;
    private javax.swing.JCheckBox checkChurrasqueira;
    private javax.swing.JCheckBox checkCinema;
    private javax.swing.JCheckBox checkCntgas;
    private javax.swing.JCheckBox checkColonial1;
    private javax.swing.JCheckBox checkEmconst1;
    private javax.swing.JCheckBox checkEspgourmet;
    private javax.swing.JCheckBox checkEspzen;
    private javax.swing.JCheckBox checkEstacionamento;
    private javax.swing.JCheckBox checkExclusividade;
    private javax.swing.JCheckBox checkFotos;
    private javax.swing.JCheckBox checkInquilino1;
    private javax.swing.JCheckBox checkInterfone;
    private javax.swing.JCheckBox checkNascente1;
    private javax.swing.JCheckBox checkNorte1;
    private javax.swing.JCheckBox checkOportunidade;
    private javax.swing.JCheckBox checkParque;
    private javax.swing.JCheckBox checkPintura1;
    private javax.swing.JCheckBox checkPiscina;
    private javax.swing.JCheckBox checkPlayground;
    private javax.swing.JCheckBox checkPoente1;
    private javax.swing.JCheckBox checkPorteiro;
    private javax.swing.JCheckBox checkPropreside1;
    private javax.swing.JCheckBox checkQuadra;
    private javax.swing.JCheckBox checkQuitado;
    private javax.swing.JCheckBox checkRevest101;
    private javax.swing.JCheckBox checkSauna;
    private javax.swing.JCheckBox checkSemir1;
    private javax.swing.JCheckBox checkSlfesta;
    private javax.swing.JCheckBox checkSljogos;
    private javax.swing.JCheckBox checkSul1;
    private javax.swing.JCheckBox checkVazio1;
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JComboBox jcbCondominio;
    private javax.swing.JComboBox jcbParceiro;
    private javax.swing.JComboBox jcbProprietario;
    private javax.swing.JLabel lblAreato;
    private javax.swing.JLabel lblAreaut;
    private javax.swing.JLabel lblAverbacao;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComapagp;
    private javax.swing.JLabel lblComarecp;
    private javax.swing.JLabel lblComvalor;
    private javax.swing.JLabel lblCondom;
    private javax.swing.JLabel lblCondominio;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblDatavenda;
    private javax.swing.JLabel lblEscritura;
    private javax.swing.JLabel lblHabite;
    private javax.swing.JLabel lblIptu;
    private javax.swing.JLabel lblLocalchaves;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblOutrosdoc;
    private javax.swing.JLabel lblPavim;
    private javax.swing.JLabel lblPostagem;
    private javax.swing.JLabel lblProprietario;
    private javax.swing.JLabel lblPtReferencia;
    private javax.swing.JLabel lblPzentrega;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTmpoconst;
    private javax.swing.JLabel lblTotun;
    private javax.swing.JLabel lblUnpandr;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorpag;
    private javax.swing.JLabel lblValorrec;
    private javax.swing.JPanel panelCaracteristica;
    private javax.swing.JPanel panelComplemento;
    private javax.swing.JPanel panelDescricao;
    private javax.swing.JPanel panelDocumentacao;
    private javax.swing.JPanel panelEndereco;
    private javax.swing.JScrollPane scrollComplemento;
    private javax.swing.JTabbedPane tabbeCadempreendimentos;
    private javax.swing.JTextField txtAreato;
    private javax.swing.JTextField txtAreaut;
    private javax.swing.JTextField txtAverbacao;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCep;
    private javax.swing.JTextField txtCompag;
    private javax.swing.JTextArea txtComplemento;
    private javax.swing.JTextField txtComrec;
    private javax.swing.JTextField txtCondom;
    private javax.swing.JTextField txtContrato;
    private javax.swing.JTextField txtDatapost;
    private javax.swing.JTextField txtDtaven;
    private javax.swing.JTextField txtEscritura;
    private javax.swing.JTextField txtHatite;
    private javax.swing.JTextField txtIptu;
    private javax.swing.JTextField txtLocchaves;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtOutrosdoc;
    private javax.swing.JTextField txtPavim;
    private javax.swing.JTextField txtPtReferencia;
    private javax.swing.JTextField txtPzentrega;
    private javax.swing.JTextField txtTotun;
    private javax.swing.JTextField txtTpoconst;
    private javax.swing.JTextField txtUnpandr;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorcom;
    private javax.swing.JTextField txtValorpag;
    private javax.swing.JTextField txtValorrec;
    // End of variables declaration//GEN-END:variables
}
