/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package s30p.view;

/**
 *
 * @author Aziz
 */
public class CadastroCondominio extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCondominio
     */
    public CadastroCondominio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        paneProprietario = new javax.swing.JPanel();
        lblProprierario = new javax.swing.JLabel();
        lblCondominio = new javax.swing.JLabel();
        lblBloco = new javax.swing.JLabel();
        lblApto = new javax.swing.JLabel();
        lblCasa = new javax.swing.JLabel();
        txtProprierario = new javax.swing.JTextField();
        txtCondominio = new javax.swing.JTextField();
        txtBloco = new javax.swing.JTextField();
        txtApto = new javax.swing.JTextField();
        txtCasa = new javax.swing.JTextField();
        paneCaracteristica = new javax.swing.JPanel();
        lblSalas = new javax.swing.JLabel();
        txtSalas = new javax.swing.JTextField();
        lblHome = new javax.swing.JLabel();
        txtHome = new javax.swing.JTextField();
        lblVaranda = new javax.swing.JLabel();
        txtVaranda = new javax.swing.JTextField();
        lblQuartos = new javax.swing.JLabel();
        txtQuartos = new javax.swing.JTextField();
        lblSuite = new javax.swing.JLabel();
        txtSuite = new javax.swing.JTextField();
        lblCloset = new javax.swing.JLabel();
        txtCloset = new javax.swing.JTextField();
        lblLavabo = new javax.swing.JLabel();
        txtLavabo = new javax.swing.JTextField();
        lblCozinha = new javax.swing.JLabel();
        txtCozinha = new javax.swing.JTextField();
        lblDespensa = new javax.swing.JLabel();
        txtDespensa = new javax.swing.JTextField();
        lblAreaserv = new javax.swing.JLabel();
        lblDependencia = new javax.swing.JLabel();
        txtAreaserv = new javax.swing.JTextField();
        txtDependeicna = new javax.swing.JTextField();
        lblEscritorio = new javax.swing.JLabel();
        txtEscritorio = new javax.swing.JTextField();
        checkRebgesso = new javax.swing.JCheckBox();
        checkGourmet = new javax.swing.JCheckBox();
        checkQcarmario = new javax.swing.JCheckBox();
        checkScarmario = new javax.swing.JCheckBox();
        checkCcarmario = new javax.swing.JCheckBox();
        checkLcarmario = new javax.swing.JCheckBox();
        checkZcarmario = new javax.swing.JCheckBox();
        checkDcarmario = new javax.swing.JCheckBox();
        checkAscarmario = new javax.swing.JCheckBox();
        checkDpcarmario = new javax.swing.JCheckBox();
        lblJardim = new javax.swing.JLabel();
        txtJardim = new javax.swing.JTextField();
        lblQuintal = new javax.swing.JLabel();
        txtQuintal = new javax.swing.JTextField();
        checkPteletronico = new javax.swing.JCheckBox();
        checkAqsolar = new javax.swing.JCheckBox();
        checkCirctv = new javax.swing.JCheckBox();
        checkGlivre = new javax.swing.JCheckBox();
        checkGpresa = new javax.swing.JCheckBox();
        checkGcoberta = new javax.swing.JCheckBox();
        checkGdescoberta = new javax.swing.JCheckBox();

        setClosable(true);
        setTitle("SU Software - Cadastro de Condomínio");
        setPreferredSize(new java.awt.Dimension(710, 438));

        lblProprierario.setText("Proprietário:");

        lblCondominio.setText("Condomínio:");

        lblBloco.setText("Bloco:");

        lblApto.setText("Apto:");

        lblCasa.setText("Casa:");

        txtCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneProprietarioLayout = new javax.swing.GroupLayout(paneProprietario);
        paneProprietario.setLayout(paneProprietarioLayout);
        paneProprietarioLayout.setHorizontalGroup(
            paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProprietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneProprietarioLayout.createSequentialGroup()
                        .addComponent(lblProprierario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProprierario, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneProprietarioLayout.createSequentialGroup()
                        .addGroup(paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCondominio)
                            .addComponent(lblBloco)
                            .addComponent(lblApto)
                            .addComponent(lblCasa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCondominio)
                            .addGroup(paneProprietarioLayout.createSequentialGroup()
                                .addGroup(paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        paneProprietarioLayout.setVerticalGroup(
            paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProprietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProprierario)
                    .addComponent(txtProprierario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCondominio)
                    .addComponent(txtCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloco)
                    .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApto)
                    .addComponent(txtApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCasa)
                    .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Descrição", paneProprietario);

        lblSalas.setText("Salas:");

        txtSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalasActionPerformed(evt);
            }
        });

        lblHome.setText("Home:");

        txtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeActionPerformed(evt);
            }
        });

        lblVaranda.setText("Varanda:");

        txtVaranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVarandaActionPerformed(evt);
            }
        });

        lblQuartos.setText("Quartos:");

        lblSuite.setText("Suíte:");

        txtSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuiteActionPerformed(evt);
            }
        });

        lblCloset.setText("Closet:");

        txtCloset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClosetActionPerformed(evt);
            }
        });

        lblLavabo.setText("Lavabo:");

        txtLavabo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLavaboActionPerformed(evt);
            }
        });

        lblCozinha.setText("Cozinha:");

        txtCozinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCozinhaActionPerformed(evt);
            }
        });

        lblDespensa.setText("Despensa:");

        lblAreaserv.setText("Área serviço:");

        lblDependencia.setText("Dependencia:");

        txtAreaserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaservActionPerformed(evt);
            }
        });

        lblEscritorio.setText("Escritóprio:");

        checkRebgesso.setText("Rebaixada gesso");

        checkGourmet.setText("Gourmet");

        checkQcarmario.setText("C/ármario");

        checkScarmario.setText("C/ármario");

        checkCcarmario.setText("C/ármario");

        checkLcarmario.setText("C/ármario");
        checkLcarmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLcarmarioActionPerformed(evt);
            }
        });

        checkZcarmario.setText("C/ármario");

        checkDcarmario.setText("C/ármario");

        checkAscarmario.setText("C/ármario");

        checkDpcarmario.setText("C/ármario");

        lblJardim.setText("Jardim:");

        lblQuintal.setText("Quintal:");

        txtQuintal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuintalActionPerformed(evt);
            }
        });

        checkPteletronico.setText("Portão eletronico");

        checkAqsolar.setText("Aquecimento solar");

        checkCirctv.setText("Circuito TV");

        checkGlivre.setText("Garagem livre");

        checkGpresa.setText("Garagem presa");
        checkGpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGpresaActionPerformed(evt);
            }
        });

        checkGcoberta.setText("Garagem coberta");

        checkGdescoberta.setText("Garagem descoberta");

        javax.swing.GroupLayout paneCaracteristicaLayout = new javax.swing.GroupLayout(paneCaracteristica);
        paneCaracteristica.setLayout(paneCaracteristicaLayout);
        paneCaracteristicaLayout.setHorizontalGroup(
            paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblDespensa)
                        .addGap(18, 18, 18)
                        .addComponent(txtDespensa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblCozinha)
                        .addGap(27, 27, 27)
                        .addComponent(txtCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblLavabo)
                        .addGap(30, 30, 30)
                        .addComponent(txtLavabo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblCloset)
                        .addGap(35, 35, 35)
                        .addComponent(txtCloset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalas)
                            .addComponent(lblHome))
                        .addGap(38, 38, 38)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblVaranda)
                        .addGap(25, 25, 25)
                        .addComponent(txtVaranda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblSuite)
                        .addGap(41, 41, 41)
                        .addComponent(txtSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblQuartos)
                        .addGap(26, 26, 26)
                        .addComponent(txtQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblAreaserv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAreaserv))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblDependencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDependeicna, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblEscritorio)
                        .addGap(18, 18, 18)
                        .addComponent(txtEscritorio)))
                .addGap(28, 28, 28)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkDcarmario)
                    .addComponent(checkAscarmario)
                    .addComponent(checkDpcarmario)
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkRebgesso)
                            .addComponent(checkGourmet)
                            .addComponent(checkQcarmario)
                            .addComponent(checkScarmario)
                            .addComponent(checkCcarmario)
                            .addComponent(checkLcarmario)
                            .addComponent(checkZcarmario))
                        .addGap(100, 100, 100)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkGdescoberta)
                            .addComponent(checkGcoberta)
                            .addComponent(checkGpresa)
                            .addComponent(checkGlivre)
                            .addComponent(checkCirctv)
                            .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuintal)
                                    .addComponent(lblJardim))
                                .addGap(68, 68, 68)
                                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQuintal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJardim, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(checkPteletronico)
                            .addComponent(checkAqsolar))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        paneCaracteristicaLayout.setVerticalGroup(
            paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalas)
                    .addComponent(txtSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkRebgesso)
                    .addComponent(lblJardim)
                    .addComponent(txtJardim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHome)
                    .addComponent(txtHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuintal)
                    .addComponent(txtQuintal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaranda)
                    .addComponent(txtVaranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkGourmet)
                    .addComponent(checkPteletronico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkAqsolar)
                .addGap(14, 14, 14)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuartos)
                    .addComponent(txtQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkQcarmario)
                    .addComponent(checkCirctv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSuite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSuite)
                    .addComponent(checkScarmario)
                    .addComponent(checkGlivre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCloset, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCloset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkCcarmario)
                        .addComponent(checkGpresa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLavabo)
                    .addComponent(txtLavabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkLcarmario)
                    .addComponent(checkGcoberta))
                .addGap(6, 6, 6)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCozinha)
                    .addComponent(txtCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkZcarmario)
                    .addComponent(checkGdescoberta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDespensa)
                    .addComponent(txtDespensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkDcarmario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAreaserv)
                    .addComponent(txtAreaserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAscarmario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDependencia)
                    .addComponent(txtDependeicna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkDpcarmario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscritorio)
                    .addComponent(txtEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Característica", paneCaracteristica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCasaActionPerformed

    private void txtSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalasActionPerformed

    private void txtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeActionPerformed

    private void txtVarandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVarandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarandaActionPerformed

    private void txtClosetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClosetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClosetActionPerformed

    private void txtLavaboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLavaboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLavaboActionPerformed

    private void txtCozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCozinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCozinhaActionPerformed

    private void txtSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuiteActionPerformed

    private void txtAreaservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaservActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaservActionPerformed

    private void checkLcarmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLcarmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkLcarmarioActionPerformed

    private void txtQuintalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuintalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuintalActionPerformed

    private void checkGpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkGpresaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAqsolar;
    private javax.swing.JCheckBox checkAscarmario;
    private javax.swing.JCheckBox checkCcarmario;
    private javax.swing.JCheckBox checkCirctv;
    private javax.swing.JCheckBox checkDcarmario;
    private javax.swing.JCheckBox checkDpcarmario;
    private javax.swing.JCheckBox checkGcoberta;
    private javax.swing.JCheckBox checkGdescoberta;
    private javax.swing.JCheckBox checkGlivre;
    private javax.swing.JCheckBox checkGourmet;
    private javax.swing.JCheckBox checkGpresa;
    private javax.swing.JCheckBox checkLcarmario;
    private javax.swing.JCheckBox checkPteletronico;
    private javax.swing.JCheckBox checkQcarmario;
    private javax.swing.JCheckBox checkRebgesso;
    private javax.swing.JCheckBox checkScarmario;
    private javax.swing.JCheckBox checkZcarmario;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblApto;
    private javax.swing.JLabel lblAreaserv;
    private javax.swing.JLabel lblBloco;
    private javax.swing.JLabel lblCasa;
    private javax.swing.JLabel lblCloset;
    private javax.swing.JLabel lblCondominio;
    private javax.swing.JLabel lblCozinha;
    private javax.swing.JLabel lblDependencia;
    private javax.swing.JLabel lblDespensa;
    private javax.swing.JLabel lblEscritorio;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblJardim;
    private javax.swing.JLabel lblLavabo;
    private javax.swing.JLabel lblProprierario;
    private javax.swing.JLabel lblQuartos;
    private javax.swing.JLabel lblQuintal;
    private javax.swing.JLabel lblSalas;
    private javax.swing.JLabel lblSuite;
    private javax.swing.JLabel lblVaranda;
    private javax.swing.JPanel paneCaracteristica;
    private javax.swing.JPanel paneProprietario;
    private javax.swing.JTextField txtApto;
    private javax.swing.JTextField txtAreaserv;
    private javax.swing.JTextField txtBloco;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JTextField txtCloset;
    private javax.swing.JTextField txtCondominio;
    private javax.swing.JTextField txtCozinha;
    private javax.swing.JTextField txtDependeicna;
    private javax.swing.JTextField txtDespensa;
    private javax.swing.JTextField txtEscritorio;
    private javax.swing.JTextField txtHome;
    private javax.swing.JTextField txtJardim;
    private javax.swing.JTextField txtLavabo;
    private javax.swing.JTextField txtProprierario;
    private javax.swing.JTextField txtQuartos;
    private javax.swing.JTextField txtQuintal;
    private javax.swing.JTextField txtSalas;
    private javax.swing.JTextField txtSuite;
    private javax.swing.JTextField txtVaranda;
    // End of variables declaration//GEN-END:variables
}
