/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package s30p.view;

/**
 *
 * @author Aziz
 */
public class CadastroUnidades extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroCondominio
     */
    public CadastroUnidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        paneProprietario = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblProprierario = new javax.swing.JLabel();
        txtProprierario = new javax.swing.JTextField();
        lblCondominio = new javax.swing.JLabel();
        txtCondominio = new javax.swing.JTextField();
        lblBloco = new javax.swing.JLabel();
        txtBloco = new javax.swing.JTextField();
        lblApto = new javax.swing.JLabel();
        txtApto = new javax.swing.JTextField();
        lblCasa = new javax.swing.JLabel();
        txtCasa = new javax.swing.JTextField();
        paneCaracteristica = new javax.swing.JPanel();
        lblSalas = new javax.swing.JLabel();
        txtSalas = new javax.swing.JTextField();
        lblHome = new javax.swing.JLabel();
        txtHome = new javax.swing.JTextField();
        lblVaranda = new javax.swing.JLabel();
        txtVaranda = new javax.swing.JTextField();
        lblQuartos = new javax.swing.JLabel();
        txtQuartos = new javax.swing.JTextField();
        lblSuite = new javax.swing.JLabel();
        txtSuite = new javax.swing.JTextField();
        lblCloset = new javax.swing.JLabel();
        txtCloset = new javax.swing.JTextField();
        lblLavabo = new javax.swing.JLabel();
        txtLavabo = new javax.swing.JTextField();
        lblCozinha = new javax.swing.JLabel();
        txtCozinha = new javax.swing.JTextField();
        lblDespensa = new javax.swing.JLabel();
        txtDespensa = new javax.swing.JTextField();
        lblAreaserv = new javax.swing.JLabel();
        lblDependencia = new javax.swing.JLabel();
        txtAreaserv = new javax.swing.JTextField();
        txtDependeicna = new javax.swing.JTextField();
        lblEscritorio = new javax.swing.JLabel();
        txtEscritorio = new javax.swing.JTextField();
        checkRebgesso = new javax.swing.JCheckBox();
        checkGourmet = new javax.swing.JCheckBox();
        checkQcarmario = new javax.swing.JCheckBox();
        checkScarmario = new javax.swing.JCheckBox();
        checkCcarmario = new javax.swing.JCheckBox();
        checkLcarmario = new javax.swing.JCheckBox();
        checkZcarmario = new javax.swing.JCheckBox();
        checkDcarmario = new javax.swing.JCheckBox();
        checkAscarmario = new javax.swing.JCheckBox();
        checkPteletronico = new javax.swing.JCheckBox();
        checkAqsolar = new javax.swing.JCheckBox();
        checkCirctv = new javax.swing.JCheckBox();
        checkGlivre = new javax.swing.JCheckBox();
        checkGpresa = new javax.swing.JCheckBox();
        checkGcoberta = new javax.swing.JCheckBox();
        checkGdescoberta = new javax.swing.JCheckBox();
        checkJardim = new javax.swing.JCheckBox();
        checkQuintal = new javax.swing.JCheckBox();
        checkDpcarmario = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBloco1 = new javax.swing.JLabel();
        txtBloco1 = new javax.swing.JTextField();
        lblApto1 = new javax.swing.JLabel();
        txtApto1 = new javax.swing.JTextField();
        lblCasa1 = new javax.swing.JLabel();
        txtCasa1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("SU Software - Cadastro de Unidades");
        setPreferredSize(new java.awt.Dimension(710, 438));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do condominio"));

        lblProprierario.setText("Proprietário:");

        lblCondominio.setText("Condomínio:");

        lblBloco.setText("Bloco:");

        lblApto.setText("Apto:");

        lblCasa.setText("Casa:");

        txtCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblProprierario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtProprierario, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCondominio)
                            .addComponent(lblBloco)
                            .addComponent(lblApto)
                            .addComponent(lblCasa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCondominio)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProprierario)
                    .addComponent(txtProprierario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCondominio)
                    .addComponent(txtCondominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloco)
                    .addComponent(txtBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApto)
                    .addComponent(txtApto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCasa)
                    .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneProprietarioLayout = new javax.swing.GroupLayout(paneProprietario);
        paneProprietario.setLayout(paneProprietarioLayout);
        paneProprietarioLayout.setHorizontalGroup(
            paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProprietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        paneProprietarioLayout.setVerticalGroup(
            paneProprietarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProprietarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Dados do imovel");

        jTabbedPane1.addTab("Descrição", paneProprietario);

        lblSalas.setText("Salas:");

        txtSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalasActionPerformed(evt);
            }
        });

        lblHome.setText("Home:");

        txtHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeActionPerformed(evt);
            }
        });

        lblVaranda.setText("Varanda:");

        txtVaranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVarandaActionPerformed(evt);
            }
        });

        lblQuartos.setText("Quartos:");

        lblSuite.setText("Suíte:");

        txtSuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuiteActionPerformed(evt);
            }
        });

        lblCloset.setText("Closet:");

        txtCloset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClosetActionPerformed(evt);
            }
        });

        lblLavabo.setText("Lavabo:");

        txtLavabo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLavaboActionPerformed(evt);
            }
        });

        lblCozinha.setText("Cozinha:");

        txtCozinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCozinhaActionPerformed(evt);
            }
        });

        lblDespensa.setText("Despensa:");

        lblAreaserv.setText("Área serviço:");

        lblDependencia.setText("Dependencia:");

        txtAreaserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaservActionPerformed(evt);
            }
        });

        lblEscritorio.setText("Escritóprio:");

        checkRebgesso.setText("Rebaixada gesso");

        checkGourmet.setText("Gourmet");
        checkGourmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGourmetActionPerformed(evt);
            }
        });

        checkQcarmario.setText("C/ármario");
        checkQcarmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkQcarmarioActionPerformed(evt);
            }
        });

        checkScarmario.setText("C/ármario");
        checkScarmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkScarmarioActionPerformed(evt);
            }
        });

        checkCcarmario.setText("C/ármario");

        checkLcarmario.setText("C/ármario");
        checkLcarmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLcarmarioActionPerformed(evt);
            }
        });

        checkZcarmario.setText("C/ármario");

        checkDcarmario.setText("C/ármario");

        checkAscarmario.setText("C/ármario");

        checkPteletronico.setText("Portão eletronico");

        checkAqsolar.setText("Aquecimento solar");

        checkCirctv.setText("Circuito TV");

        checkGlivre.setText("Garagem livre");

        checkGpresa.setText("Garagem presa");
        checkGpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGpresaActionPerformed(evt);
            }
        });

        checkGcoberta.setText("Garagem coberta");
        checkGcoberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGcobertaActionPerformed(evt);
            }
        });

        checkGdescoberta.setText("Garagem descoberta");
        checkGdescoberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGdescobertaActionPerformed(evt);
            }
        });

        checkJardim.setText("Jardim");

        checkQuintal.setText("Quintal");

        checkDpcarmario.setText("C/ármario");

        javax.swing.GroupLayout paneCaracteristicaLayout = new javax.swing.GroupLayout(paneCaracteristica);
        paneCaracteristica.setLayout(paneCaracteristicaLayout);
        paneCaracteristicaLayout.setHorizontalGroup(
            paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalas)
                            .addComponent(lblHome))
                        .addGap(38, 38, 38)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblEscritorio)
                        .addGap(18, 18, 18)
                        .addComponent(txtEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVaranda)
                            .addComponent(lblQuartos))
                        .addGap(25, 25, 25)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVaranda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCloset, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLavabo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblSuite)
                    .addComponent(lblCloset)
                    .addComponent(lblLavabo)
                    .addComponent(lblCozinha)
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblDespensa)
                        .addGap(18, 18, 18)
                        .addComponent(txtDespensa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblAreaserv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAreaserv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(lblDependencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDependeicna, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkGourmet)
                            .addComponent(checkRebgesso)
                            .addComponent(checkLcarmario)
                            .addComponent(checkZcarmario)
                            .addComponent(checkCcarmario)
                            .addComponent(checkScarmario)
                            .addComponent(checkQcarmario)
                            .addComponent(checkDcarmario)
                            .addComponent(checkAscarmario))
                        .addGap(96, 96, 96)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkGcoberta)
                            .addComponent(checkGpresa)
                            .addComponent(checkGlivre)
                            .addComponent(checkCirctv)
                            .addComponent(checkPteletronico)
                            .addComponent(checkAqsolar)
                            .addComponent(checkJardim)
                            .addComponent(checkQuintal)
                            .addComponent(checkGdescoberta)))
                    .addComponent(checkDpcarmario))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        paneCaracteristicaLayout.setVerticalGroup(
            paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalas)
                    .addComponent(txtSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkRebgesso)
                    .addComponent(checkJardim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHome)
                    .addComponent(txtHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkQuintal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaranda)
                    .addComponent(txtVaranda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkPteletronico)
                    .addComponent(checkGourmet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addComponent(checkAqsolar)
                        .addGap(5, 5, 5)
                        .addComponent(checkCirctv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkGlivre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkGpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkGcoberta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkGdescoberta))
                    .addGroup(paneCaracteristicaLayout.createSequentialGroup()
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuartos)
                            .addComponent(txtQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkScarmario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSuite)
                            .addComponent(txtSuite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkQcarmario))
                        .addGap(1, 1, 1)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkCcarmario)
                            .addComponent(lblCloset, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCloset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLavabo)
                            .addComponent(txtLavabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkLcarmario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCozinha)
                            .addComponent(txtCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkZcarmario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDespensa)
                            .addComponent(txtDespensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkDcarmario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAreaserv)
                            .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAreaserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(checkAscarmario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDependencia)
                            .addComponent(txtDependeicna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkDpcarmario))))
                .addGap(83, 83, 83)
                .addGroup(paneCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscritorio)
                    .addComponent(txtEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Característica", paneCaracteristica);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Complemento"));

        lblBloco1.setText("Bloco:");

        lblApto1.setText("Apto:");

        lblCasa1.setText("Casa:");

        txtCasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCasa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBloco1)
                    .addComponent(lblApto1)
                    .addComponent(lblCasa1))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBloco1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApto1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloco1)
                    .addComponent(txtBloco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApto1)
                    .addComponent(txtApto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCasa1)
                    .addComponent(txtCasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName("Complemento");

        jTabbedPane1.addTab("Endereço/Complemento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCasaActionPerformed

    private void txtSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalasActionPerformed

    private void txtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeActionPerformed

    private void txtVarandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVarandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarandaActionPerformed

    private void txtClosetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClosetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClosetActionPerformed

    private void txtLavaboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLavaboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLavaboActionPerformed

    private void txtCozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCozinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCozinhaActionPerformed

    private void txtSuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuiteActionPerformed

    private void txtAreaservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaservActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaservActionPerformed

    private void checkLcarmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLcarmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkLcarmarioActionPerformed

    private void checkGpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkGpresaActionPerformed

    private void checkGcobertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGcobertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkGcobertaActionPerformed

    private void checkQcarmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkQcarmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkQcarmarioActionPerformed

    private void checkGourmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGourmetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkGourmetActionPerformed

    private void checkScarmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkScarmarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkScarmarioActionPerformed

    private void checkGdescobertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGdescobertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkGdescobertaActionPerformed

    private void txtCasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCasa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCasa1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAqsolar;
    private javax.swing.JCheckBox checkAscarmario;
    private javax.swing.JCheckBox checkCcarmario;
    private javax.swing.JCheckBox checkCirctv;
    private javax.swing.JCheckBox checkDcarmario;
    private javax.swing.JCheckBox checkDpcarmario;
    private javax.swing.JCheckBox checkGcoberta;
    private javax.swing.JCheckBox checkGdescoberta;
    private javax.swing.JCheckBox checkGlivre;
    private javax.swing.JCheckBox checkGourmet;
    private javax.swing.JCheckBox checkGpresa;
    private javax.swing.JCheckBox checkJardim;
    private javax.swing.JCheckBox checkLcarmario;
    private javax.swing.JCheckBox checkPteletronico;
    private javax.swing.JCheckBox checkQcarmario;
    private javax.swing.JCheckBox checkQuintal;
    private javax.swing.JCheckBox checkRebgesso;
    private javax.swing.JCheckBox checkScarmario;
    private javax.swing.JCheckBox checkZcarmario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblApto;
    private javax.swing.JLabel lblApto1;
    private javax.swing.JLabel lblAreaserv;
    private javax.swing.JLabel lblBloco;
    private javax.swing.JLabel lblBloco1;
    private javax.swing.JLabel lblCasa;
    private javax.swing.JLabel lblCasa1;
    private javax.swing.JLabel lblCloset;
    private javax.swing.JLabel lblCondominio;
    private javax.swing.JLabel lblCozinha;
    private javax.swing.JLabel lblDependencia;
    private javax.swing.JLabel lblDespensa;
    private javax.swing.JLabel lblEscritorio;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLavabo;
    private javax.swing.JLabel lblProprierario;
    private javax.swing.JLabel lblQuartos;
    private javax.swing.JLabel lblSalas;
    private javax.swing.JLabel lblSuite;
    private javax.swing.JLabel lblVaranda;
    private javax.swing.JPanel paneCaracteristica;
    private javax.swing.JPanel paneProprietario;
    private javax.swing.JTextField txtApto;
    private javax.swing.JTextField txtApto1;
    private javax.swing.JTextField txtAreaserv;
    private javax.swing.JTextField txtBloco;
    private javax.swing.JTextField txtBloco1;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JTextField txtCasa1;
    private javax.swing.JTextField txtCloset;
    private javax.swing.JTextField txtCondominio;
    private javax.swing.JTextField txtCozinha;
    private javax.swing.JTextField txtDependeicna;
    private javax.swing.JTextField txtDespensa;
    private javax.swing.JTextField txtEscritorio;
    private javax.swing.JTextField txtHome;
    private javax.swing.JTextField txtLavabo;
    private javax.swing.JTextField txtProprierario;
    private javax.swing.JTextField txtQuartos;
    private javax.swing.JTextField txtSalas;
    private javax.swing.JTextField txtSuite;
    private javax.swing.JTextField txtVaranda;
    // End of variables declaration//GEN-END:variables
}
