/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package s30p.view;

/**
 *
 * @author koonjshah
 */
public class ListagemProprietario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListagemProprietario
     */
    public ListagemProprietario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        S30PPUEntityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("S30PPU").createEntityManager();
        jScrollPane1 = new javax.swing.JScrollPane();
        proprietariosTable = new javax.swing.JTable();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(735, 435));

        proprietariosTable.getTableHeader().setReorderingAllowed(false);
        proprietariosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proprietariosTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(proprietariosTable);
        proprietariosTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proprietariosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proprietariosTableMouseClicked
      int selectedRow = proprietariosTable.getSelectedRow();
//      model.beans.Conta prop = proprietariosList.get(selectedRow);
//        System.out.println("id:"+prop.getIdproprietarios());
//        System.out.println("nome: "+prop.getNome());
        
    }//GEN-LAST:event_proprietariosTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager S30PPUEntityManager0;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable proprietariosTable;
    // End of variables declaration//GEN-END:variables
}
